from .settings_ventana import TITULO_VENTANA, DIMENSION_VENTANA, COLOR_VENTANA, COLOR_TRENES, BORDE_TRENES, COLOR_ESTACIONES, BORDE_ESTACIONES

__all__ = [
    "TITULO_VENTANA",
    "DIMENSION_VENTANA",
    "COLOR_VENTANA",
    "COLOR_TRENES",
    "BORDE_TRENES",
    "COLOR_ESTACIONES",
    "BORDE_ESTACIONES",
]
