TITULO_VENTANA = "Gestion de Trenes"
DIMENSION_VENTANA = "800x600"
COLOR_VENTANA = "#f5f2f4"

COLOR_TRENES = '#ffc1a3'
BORDE_TRENES = '#ff7f50'
COLOR_ESTACIONES = '#a3d3ff'
BORDE_ESTACIONES = '#1f75fe'